# ベースイメージとして Ruby 3.3.6 を使用
FROM ruby:3.3.6

# 言語設定とタイムゾーン設定
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# Node.js、Yarn、その他必要なパッケージのインストール
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
&& wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn vim

# アプリケーション用ディレクトリの作成と作業ディレクトリの設定
RUN mkdir /myapp
WORKDIR /myapp
RUN gem install bundler

# ホストマシンのカレントディレクトリからコンテナの /myapp ディレクトリへファイルをコピー
COPY . /myapp
